name: Test
on:
  push:
  workflow_dispatch:
    inputs:
      test:
        type: boolean
        description: Test
        default: false
      test2:
        type: boolean
        description: Test 2
        default: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ vars.TEST_VAR }}
  test2:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.test && inputs.test2 }}
